# Generated by Django 2.2.2 on 2019-07-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("catapp", "0002_auto_20190704_0845")]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="type",
            field=models.CharField(
                choices=[("LANDED", "Landed"), ("CONDO", "Condominium")],
                default="LANDED",
                max_length=100,
            ),
        )
    ]
